Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,27 +1,29 @@
-name: Build
+# Manual workflow to deploy to Firebase Hosting
+name: Manual Firebase Deploy
+
 on:
-  workflow_dispatch:
-      inputs:
-        package_name:
-          description: "Package name of the game:"
-          required: true
+  workflow_dispatch: # This allows manual triggering from the GitHub Actions tab
 
 jobs:
-  build:
+  build_and_deploy:
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v3
-    - uses: actions/setup-java@v3
-      with:
-        distribution: temurin
-        java-version: 11
-        cache: gradle
-    - run: |
-        chmod +x ./gradlew
-        sed -i 's/moduleDescription = "/moduleDescription = "(${{ github.event.inputs.package_name }}) /g' module.gradle
-        sed -i "s/com.game.packagename/${{ github.event.inputs.package_name }}/g" module/src/main/cpp/game.h
-        ./gradlew :module:assembleRelease
-    - uses: actions/upload-artifact@v3
-      with:
-        name: zygisk-il2cppdumper
-        path: out/magisk_module_release/
+      - uses: actions/checkout@v4
+      - name: Set up Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: '20' # Use Node.js version 20
+      - name: Debug: List react-scripts in node_modules
+        run: ls -al node_modules/react-scripts || echo "react-scripts directory not found"
+      - name: Debug: List react-scripts executable in .bin
+        run: ls -al node_modules/.bin/react-scripts || echo "react-scripts executable not found in .bin"
+      - name: Install Dependencies
+        run: npm ci
+      - name: Build React App
+        run: npm run build
+      - uses: FirebaseExtended/action-hosting-deploy@v0
+        with:
+          repoToken: ${{ secrets.GITHUB_TOKEN }}
+          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_GYM_CHECK_IN_D1BF5 }}
+          channelId: live
+          projectId: gym-check-in-d1bf5
